/**
 * Paper Fold, as data.
 *
 * A square sheet is folded in half two or three times, a hole is punched through
 * the folded stack, and the question is what the sheet looks like opened out.
 * There is no way to answer it except by generating the picture — no rule of
 * thumb, no counting, no motor skill, and nothing to react to. Of everything in
 * this app it is the task that asks for the most mental imagery and the least of
 * anything else, which is why it is worth having beside the rotation games.
 *
 * ## Continuous, not a grid
 *
 * The sheet is the unit square and a punch is a point in it, rather than a cell
 * in some N×N grid. Folding halves a rectangle, so three folds off an 8-wide
 * grid leaves a one-cell strip, and a hole in it is a hole the width of the
 * folded paper. Points have no such floor.
 *
 * It also makes equality exact. Every coordinate here starts at a half or a
 * sixth of a half and is only ever halved or reflected across a halfway line, so
 * every x and y is a dyadic rational — which a float represents exactly. Two
 * patterns are the same pattern if their numbers match, with no epsilon and no
 * "near enough", and that matters because the whole item is broken if a
 * distractor is secretly the answer.
 */

export type Axis = 'vertical' | 'horizontal';

export interface Point {
  x: number;
  y: number;
}

/** Half-open in spirit: `x0 <= x <= x1`. In sheet units, so always within 0..1. */
export interface Rect {
  x0: number;
  y0: number;
  x1: number;
  y1: number;
}

/**
 * One fold, named by the half that stays put. The other half is the one that
 * moves — it lifts over the crease and lands on the half named here.
 */
export type Fold =
  | { axis: 'vertical'; keep: 'left' | 'right' }
  | { axis: 'horizontal'; keep: 'top' | 'bottom' };

export const SHEET: Rect = { x0: 0, y0: 0, x1: 1, y1: 1 };

export interface FoldRound {
  folds: readonly Fold[];
  /**
   * The sheet at each stage: `frames[0]` is the whole square, and each one after
   * it is what is left after the fold at the same index. The last is the folded
   * stack the punches go through.
   */
  frames: readonly Rect[];
  /** Where the holes are punched, in the last frame. */
  punches: readonly Point[];
  /** Four unfolded sheets. Exactly one of them is right. */
  options: readonly (readonly Point[])[];
  answerIndex: number;
}

const ALL_FOLDS: readonly Fold[] = [
  { axis: 'vertical', keep: 'left' },
  { axis: 'vertical', keep: 'right' },
  { axis: 'horizontal', keep: 'top' },
  { axis: 'horizontal', keep: 'bottom' },
];

/** Where the crease falls, in sheet units. */
export function creaseAt(rect: Rect, fold: Fold): number {
  return fold.axis === 'vertical' ? (rect.x0 + rect.x1) / 2 : (rect.y0 + rect.y1) / 2;
}

/** The rectangle that is left once the fold is made. */
export function applyFold(rect: Rect, fold: Fold): Rect {
  const line = creaseAt(rect, fold);

  if (fold.axis === 'vertical') {
    return fold.keep === 'left' ? { ...rect, x1: line } : { ...rect, x0: line };
  }
  return fold.keep === 'top' ? { ...rect, y1: line } : { ...rect, y0: line };
}

/** The half that lifts over the crease. Drawn as a ghost in the fold diagram. */
export function movedHalf(rect: Rect, fold: Fold): Rect {
  const line = creaseAt(rect, fold);

  if (fold.axis === 'vertical') {
    return fold.keep === 'left' ? { ...rect, x0: line } : { ...rect, x1: line };
  }
  return fold.keep === 'top' ? { ...rect, y0: line } : { ...rect, y1: line };
}

export function frames(folds: readonly Fold[]): Rect[] {
  const out: Rect[] = [SHEET];
  for (const fold of folds) out.push(applyFold(out[out.length - 1], fold));
  return out;
}

export function reflect(point: Point, axis: Axis, line: number): Point {
  return axis === 'vertical'
    ? { x: 2 * line - point.x, y: point.y }
    : { x: point.x, y: 2 * line - point.y };
}

/**
 * One fold undone: every hole, plus its twin on the other side of the crease.
 *
 * `rect` is the sheet *before* that fold was made, which is what puts the crease
 * in the right place — undoing the second of two folds is a reflection across
 * the middle of a half-sheet, not across the middle of the sheet.
 */
export function unfoldOnce(points: readonly Point[], fold: Fold, rect: Rect): Point[] {
  const line = creaseAt(rect, fold);
  return points.flatMap((point) => [point, reflect(point, fold.axis, line)]);
}

/** Every fold undone, last one first. */
export function unfold(punches: readonly Point[], folds: readonly Fold[]): Point[] {
  const stages = frames(folds);
  let points = [...punches];

  for (let i = folds.length - 1; i >= 0; i -= 1) {
    points = unfoldOnce(points, folds[i], stages[i]);
  }
  return points;
}

/**
 * A pattern's identity, for telling two of them apart.
 *
 * Order is not part of a pattern — the same holes generated by two different
 * routes are the same sheet — so this sorts before joining. The rounding is
 * belt and braces: see the note at the top about why the numbers are exact.
 */
export function patternKey(points: readonly Point[]): string {
  return points
    .map((point) => `${point.x.toFixed(6)},${point.y.toFixed(6)}`)
    .sort()
    .join(' ');
}

/** Across the sheet's own middle, which is not usually the last crease. */
function flipSheet(points: readonly Point[], axis: Axis): Point[] {
  return points.map((point) => reflect(point, axis, 0.5));
}

/** A quarter-turn about the middle of the sheet. */
function turnSheet(points: readonly Point[]): Point[] {
  return points.map((point) => ({ x: 1 - point.y, y: point.x }));
}

/**
 * Where a hole can go: three positions across and three down, inset from the
 * edges of the folded stack.
 *
 * Inset rather than on the crease. A hole punched exactly on a fold line is its
 * own reflection, so it opens out to half as many holes as the fold count says
 * it should — a correct answer that looks like a miscount, which is the one
 * thing an item like this must never look like.
 */
function punchSites(rect: Rect): Point[] {
  const sites: Point[] = [];
  const at = (low: number, high: number, step: number) =>
    low + ((step + 0.5) / 3) * (high - low);

  for (let row = 0; row < 3; row += 1) {
    for (let column = 0; column < 3; column += 1) {
      sites.push({ x: at(rect.x0, rect.x1, column), y: at(rect.y0, rect.y1, row) });
    }
  }
  return sites;
}

function pick<T>(items: readonly T[], random: () => number): T {
  return items[Math.floor(random() * items.length)];
}

function take<T>(items: readonly T[], count: number, random: () => number): T[] {
  const pool = [...items];
  const out: T[] = [];

  for (let i = 0; i < count && pool.length > 0; i += 1) {
    out.push(...pool.splice(Math.floor(random() * pool.length), 1));
  }
  return out;
}

/**
 * A fold sequence. Consecutive folds never share an axis.
 *
 * Two folds down the same axis in a row is a legal thing to do to a piece of
 * paper and a bad thing to ask about: the sheet becomes a thin strip, the holes
 * end up in a line, and the item stops testing anything but arithmetic. One
 * across, one down keeps the folded stack roughly square.
 */
function foldSequence(count: number, random: () => number): Fold[] {
  const folds: Fold[] = [pick(ALL_FOLDS, random)];

  while (folds.length < count) {
    const previous = folds[folds.length - 1];
    folds.push(
      pick(
        ALL_FOLDS.filter((fold) => fold.axis !== previous.axis),
        random,
      ),
    );
  }
  return folds;
}

/**
 * A round.
 *
 * The wrong answers are the part worth reading. All three carry exactly as many
 * holes as the right one, which rules out the shortcut of counting them and
 * picking the option with the number that fits the fold count — that would be a
 * correct answer arrived at without imagining anything. Each is also a mistake
 * somebody actually makes: the right holes in the wrong orientation, or a
 * correctly-opened sheet that was punched somewhere else.
 */
export function buildRound(random: () => number = Math.random): FoldRound {
  // Three folds double the holes one more time, so the punch count comes down
  // to keep the opened sheet legible: eight holes is a pattern, sixteen is
  // confetti.
  const foldCount = random() < 0.5 ? 2 : 3;
  const folds = foldSequence(foldCount, random);
  const stages = frames(folds);
  const folded = stages[stages.length - 1];

  const punchCount = foldCount === 3 || random() < 0.4 ? 1 : 2;
  const punches = take(punchSites(folded), punchCount, random);

  const answer = unfold(punches, folds);
  const answerKey = patternKey(answer);

  const wrong: Point[][] = [];
  const seen = new Set([answerKey]);

  const consider = (candidate: Point[]) => {
    const key = patternKey(candidate);
    if (seen.has(key)) return;
    seen.add(key);
    wrong.push(candidate);
  };

  consider(flipSheet(answer, 'vertical'));
  consider(flipSheet(answer, 'horizontal'));
  consider(turnSheet(answer));

  // Backstop, and the reason this loop is bounded rather than a `while`: a
  // symmetrical pattern is its own reflection, so the three above can collapse
  // to one, and the same punch sites can come up twice. Correctly-opened sheets
  // punched somewhere else fill the gap.
  for (let attempt = 0; attempt < 40 && wrong.length < 3; attempt += 1) {
    consider(unfold(take(punchSites(folded), punchCount, random), folds));
  }

  const options = [...wrong.slice(0, 3), answer];
  // Fisher-Yates, so the answer is not always last.
  for (let i = options.length - 1; i > 0; i -= 1) {
    const j = Math.floor(random() * (i + 1));
    [options[i], options[j]] = [options[j], options[i]];
  }

  return {
    folds,
    frames: stages,
    punches,
    options,
    answerIndex: options.findIndex((option) => patternKey(option) === answerKey),
  };
}
